# Generated by Django 5.1.3 on 2024-11-17 18:51

import beabee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Insulting community members', 'Insulting'), ('Publishing obscene content', 'Obscene Content'), ('Spam', 'Spam')], max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('details', models.CharField(default='No Details', max_length=50)),
                ('group', models.CharField(choices=[('CS-31', 'Cs 31'), ('CS-32', 'Cs 32'), ('CS-33', 'Cs 33'), ('CS-34', 'Cs 34'), ('CS-41', 'Cs 41'), ('CS-42', 'Cs 42'), ('CS-43', 'Cs 43'), ('CS-44', 'Cs 44')], max_length=50)),
                ('type', models.CharField(choices=[('Annual exam', 'Annual Exam'), ('Annual exam (retake)', 'Annual Exam Ret'), ('Year session', 'Year Session'), ('Year session (retake)', 'Year Session Ret'), ('Semester session', 'Sem Session'), ('Semester session (retake)', 'Sem Session Ret'), ('Modular control work', 'Modular Control Work'), ('Modular control work (retake)', 'Modular Control Work Ret'), ('Control work', 'Control Work'), ('Control work (retake)', 'Control Work Ret'), ('Specific type', 'Specific Type')], default='Specific type', max_length=50)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Math/Physics', 'Math Physics'), ('Prog/Networks', 'Prog Networks'), ('Lang/Culture', 'Lang Culture')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('for_group', models.CharField(choices=[('CS-31', 'Cs 31'), ('CS-32', 'Cs 32'), ('CS-33', 'Cs 33'), ('CS-34', 'Cs 34'), ('CS-41', 'Cs 41'), ('CS-42', 'Cs 42'), ('CS-43', 'Cs 43'), ('CS-44', 'Cs 44')], default='No group', max_length=50)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=beabee.models.info_media_path)),
                ('description', models.CharField(default='No Description', max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=beabee.models.news_media_path)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(default='No description', max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=beabee.models.photo_path)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_avatar', models.ImageField(upload_to=beabee.models.teachers_avatars_path)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('degree', models.CharField(choices=[("Bachelor's Degree", 'Bachelor'), ("Master's Degree", 'Master'), ('Candidate of Sciences', 'Candidate'), ('Doctor of Sciences', 'Doctor')], max_length=50)),
                ('email', models.EmailField(default='noemail@example.com', max_length=254)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
