# Generated by Django 5.1.3 on 2024-12-02 02:09

import beabee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Insulting community members', 'Insulting community members'), ('Publishing obscene content', 'Publishing obscene content'), ('Spam', 'Spam')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('details', models.CharField(default='No Details', max_length=50)),
                ('group', models.CharField(choices=[('CS-31', 'CS-31'), ('CS-32', 'CS-32'), ('CS-33', 'CS-33'), ('CS-34', 'CS-34'), ('CS-41', 'CS-41'), ('CS-42', 'CS-42'), ('CS-43', 'CS-43'), ('CS-44', 'CS-44'), ('No group', 'No group')], max_length=10, verbose_name='Group')),
                ('type', models.CharField(choices=[('Annual exam', 'Annual exam'), ('Annual exam (retake)', 'Annual exam (retake)'), ('Year session', 'Year session'), ('Year session (retake)', 'Year session (retake)'), ('Semester session', 'Semester session'), ('Semester session (retake)', 'Semester session (retake)'), ('Module control work', 'Module control work'), ('Module control work (retake)', 'Module control work (retake)'), ('Control work', 'Control work'), ('Control work (retake)', 'Control work (retake)'), ('Specific type', 'Specific type')], default='Specific type', max_length=30, verbose_name='Type')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Math/Physics', 'Math/Physics'), ('Prog/Networks', 'Prog/Networks'), ('Lang/Culture', 'Lang/Culture')], db_index=True, max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('for_group', models.CharField(choices=[('CS-31', 'CS-31'), ('CS-32', 'CS-32'), ('CS-33', 'CS-33'), ('CS-34', 'CS-34'), ('CS-41', 'CS-41'), ('CS-42', 'CS-42'), ('CS-43', 'CS-43'), ('CS-44', 'CS-44'), ('No group', 'No group')], default='No group', max_length=10, verbose_name='For group')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(upload_to=beabee.models.info_media_path)),
                ('description', models.CharField(default='No Description', max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LatestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Joined', 'Joined'), ('Banned', 'Banned')], default='Created', max_length=10, verbose_name='Status')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=beabee.models.news_media_path)),
                ('title', models.CharField(db_index=True, max_length=30)),
                ('description', models.CharField(default='No description', max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=beabee.models.photo_path)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentInTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('group', models.CharField(choices=[('CS-31', 'CS-31'), ('CS-32', 'CS-32'), ('CS-33', 'CS-33'), ('CS-34', 'CS-34'), ('CS-41', 'CS-41'), ('CS-42', 'CS-42'), ('CS-43', 'CS-43'), ('CS-44', 'CS-44'), ('No group', 'No group')], max_length=10)),
                ('subgroup', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('email', models.EmailField(default='noemail@example.com', max_length=254)),
                ('role', models.CharField(choices=[('Headman', 'Headman'), ('Deputy headman', 'Deputy headman'), ('Student', 'Student')], max_length=20)),
                ('location', models.CharField(choices=[('In Ukraine', 'In Ukraine'), ('Lives aboard', 'Lives aboard')], max_length=15)),
            ],
            options={
                'ordering': ['-last_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('group', models.CharField(choices=[('CS-31', 'CS-31'), ('CS-32', 'CS-32'), ('CS-33', 'CS-33'), ('CS-34', 'CS-34'), ('CS-41', 'CS-41'), ('CS-42', 'CS-42'), ('CS-43', 'CS-43'), ('CS-44', 'CS-44'), ('No group', 'No group')], default='NO_GROUP', max_length=10, verbose_name='Group')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Success', 'Success'), ('Warning', 'Warning'), ('Error', 'Error')], max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show_once', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotificationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_avatar', models.ImageField(upload_to=beabee.models.teachers_avatars_path)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('degree', models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Candidate of Sciences', 'Candidate of Sciences'), ('Doctor of Sciences', 'Doctor of Sciences')], default="Bachelor's Degree", max_length=30, verbose_name='Degree')),
                ('email', models.EmailField(default='noemail@example.com', max_length=254)),
                ('math_phy_count', models.PositiveIntegerField(default=0)),
                ('prog_net_count', models.PositiveIntegerField(default=0)),
                ('lang_cul_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
