# Generated by Django 5.1.3 on 2024-12-23 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beabee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='banned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ban',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homework',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_homeworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importantinfo',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_posters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentintable',
            index=models.Index(fields=['last_name'], name='beabee_stud_last_na_6ea7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentintable',
            index=models.Index(fields=['surname'], name='beabee_stud_surname_cfece1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentintable',
            index=models.Index(fields=['role'], name='beabee_stud_role_8a453c_idx'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_homeworks', to='beabee.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beabee.subject'),
        ),
        migrations.AddField(
            model_name='systemnotificationview',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beabee.systemnotifications'),
        ),
        migrations.AddField(
            model_name='systemnotificationview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='beabee.subject'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_homeworks', to='beabee.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beabee.teacher'),
        ),
        migrations.AddIndex(
            model_name='importantinfo',
            index=models.Index(fields=['posted_by'], name='beabee_impo_posted__12c80a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemnotificationview',
            unique_together={('user', 'notification')},
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['last_name', 'degree'], name='beabee_teac_last_na_f3a79d_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['title'], name='beabee_home_title_c25281_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['type'], name='beabee_home_type_5d405a_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date_time'], name='beabee_exam_date_ti_11b6f9_idx'),
        ),
    ]
