# Generated by Django 5.1.3 on 2024-11-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('group', models.CharField(choices=[('CS-31', 'Cs 31'), ('CS-32', 'Cs 32'), ('CS-33', 'Cs 33'), ('CS-34', 'Cs 34'), ('CS-41', 'Cs 41'), ('CS-42', 'Cs 42'), ('CS-43', 'Cs 43'), ('CS-44', 'Cs 44')], max_length=5)),
                ('subgroup', models.CharField(choices=[('1', 'First'), ('2', 'Second')], max_length=2)),
                ('email', models.EmailField(default='<--- noemail@example.com --->', max_length=254)),
                ('role', models.CharField(choices=[('Headman', 'Headman'), ('Deputy headman', 'D Headman'), ('Student', 'Student')], max_length=15)),
                ('location', models.CharField(choices=[('In Ukraine', 'In Ukr'), (' Lives aboard', 'Aboard')], max_length=13)),
            ],
        ),
    ]
