# Generated by Django 4.0.4 on 2024-11-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinfo',
            name='description',
            field=models.CharField(default='No Description', max_length=1555),
        ),
    ]
