# Generated by Django 4.0.4 on 2024-10-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
