# Generated by Django 5.1.3 on 2024-12-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0003_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
