# Generated by Django 5.1.3 on 2024-11-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0003_studentintable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentintable',
            name='location',
            field=models.CharField(choices=[('In Ukraine', 'In Ukr'), ('Lives aboard', 'Aboard')], max_length=13),
        ),
        migrations.CreateModel(
            name='StudentsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('CS-31', 'Cs 31'), ('CS-32', 'Cs 32'), ('CS-33', 'Cs 33'), ('CS-34', 'Cs 34'), ('CS-41', 'Cs 41'), ('CS-42', 'Cs 42'), ('CS-43', 'Cs 43'), ('CS-44', 'Cs 44')], max_length=5)),
                ('students', models.ManyToManyField(to='beabee.studentintable')),
            ],
        ),
    ]
