# Generated by Django 5.1.3 on 2024-11-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0003_alter_homework_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinfo',
            name='description',
            field=models.CharField(default='No Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(default='No description', max_length=1000),
        ),
    ]
