# Generated by Django 4.0.4 on 2024-11-03 18:05

import beabee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0003_alter_importantinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.ImageField(upload_to=beabee.models.news_media_path),
        ),
    ]
