# Generated by Django 5.1.3 on 2024-11-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0004_alter_importantinfo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinfo',
            name='description',
            field=models.CharField(default='No Description', max_length=1200),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(default='No description', max_length=1200),
        ),
    ]
