# Generated by Django 4.0.4 on 2024-11-03 18:06

import beabee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0004_alter_news_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.FileField(upload_to=beabee.models.news_media_path),
        ),
    ]
