# Generated by Django 5.1.3 on 2024-11-22 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0004_alter_studentintable_location_studentstable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstable',
            old_name='group',
            new_name='table_name',
        ),
        migrations.AddField(
            model_name='studentstable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_table', to=settings.AUTH_USER_MODEL),
        ),
    ]
