# Generated by Django 5.1.3 on 2024-12-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0005_alter_homework_created_at_alter_news_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='added_by',
        ),
    ]
