# Generated by Django 4.0.4 on 2024-11-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0005_alter_news_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(default='No description', max_length=1555),
        ),
    ]
