# Generated by Django 5.1.3 on 2024-11-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0005_alter_importantinfo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lang_cul_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='math_phy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='prog_net_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homework',
            name='for_group',
            field=models.CharField(choices=[('CS-31', 'Cs 31'), ('CS-32', 'Cs 32'), ('CS-33', 'Cs 33'), ('CS-34', 'Cs 34'), ('CS-41', 'Cs 41'), ('CS-42', 'Cs 42'), ('CS-43', 'Cs 43'), ('CS-44', 'Cs 44')], default='No group', max_length=50),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homework',
            name='type',
            field=models.CharField(choices=[('Math/Physics', 'Math Physics'), ('Prog/Networks', 'Prog Networks'), ('Lang/Culture', 'Lang Culture')], max_length=50),
        ),
    ]
