# Generated by Django 5.1.3 on 2024-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0005_rename_group_studentstable_table_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.CharField(choices=[('CS-31', 'Cs 31'), ('CS-32', 'Cs 32'), ('CS-33', 'Cs 33'), ('CS-34', 'Cs 34'), ('CS-41', 'Cs 41'), ('CS-42', 'Cs 42'), ('CS-43', 'Cs 43'), ('CS-44', 'Cs 44')], default='NO_GROUP', max_length=8),
        ),
        migrations.DeleteModel(
            name='StudentsTable',
        ),
    ]
