# Generated by Django 5.1.3 on 2024-11-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0006_teacher_lang_cul_count_teacher_math_phy_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='lang_cul_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='math_phy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='prog_net_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
