# Generated by Django 5.1.3 on 2024-12-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0007_alter_teacher_lang_cul_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homework',
            name='type',
            field=models.CharField(choices=[('Math/Physics', 'Math Physics'), ('Prog/Networks', 'Prog Networks'), ('Lang/Culture', 'Lang Culture')], max_length=13),
        ),
    ]
