# Generated by Django 4.0.4 on 2024-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0007_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
