# Generated by Django 5.1.3 on 2024-12-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0008_alter_homework_title_alter_homework_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='for_group',
            field=models.CharField(choices=[('CS-31', 'Cs 31'), ('CS-32', 'Cs 32'), ('CS-33', 'Cs 33'), ('CS-34', 'Cs 34'), ('CS-41', 'Cs 41'), ('CS-42', 'Cs 42'), ('CS-43', 'Cs 43'), ('CS-44', 'Cs 44')], default='No group', max_length=8),
        ),
        migrations.AlterField(
            model_name='importantinfo',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
