# Generated by Django 4.0.4 on 2024-11-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0008_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinfo',
            name='description',
            field=models.CharField(default='No Description', max_length=2555),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(default='No description', max_length=2555),
        ),
    ]
