# Generated by Django 5.1.3 on 2024-12-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0009_alter_homework_for_group_alter_importantinfo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('important_info', 'Important info'), ('homework', 'Homework')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
