# Generated by Django 4.0.4 on 2024-11-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0009_alter_importantinfo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=20),
        ),
    ]
