# Generated by Django 4.0.4 on 2024-11-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0010_alter_teacher_first_name_alter_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
        ),
    ]
