# Generated by Django 5.1.3 on 2024-12-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0010_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
