# Generated by Django 4.0.4 on 2024-11-04 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0011_teacher_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='subjects',
        ),
    ]
