# Generated by Django 5.1.3 on 2024-12-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0011_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Success', 'Success'), ('Warning', 'Warning'), ('Error', 'Error')], max_length=7)),
                ('description', models.CharField(max_length=150)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
