# Generated by Django 4.0.4 on 2024-11-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0012_rename_subject_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('Annual exam', 'Annual Exam'), ('Annual exam (retake)', 'Annual Exam Ret'), ('Year session', 'Year Session'), ('Year session (retake)', 'Year Session Ret'), ('Semester session', 'Sem Session'), ('Semester session (retake)', 'Sem Session Ret'), ('Modular control work', 'Modular Control Work'), ('Modular control work (retake)', 'Modular Control Work Ret'), ('Control work', 'Control Work'), ('Control work (retake)', 'Control Work Ret'), ('Specific type', 'Specific Type')], default='Specific type', max_length=50),
        ),
    ]
