# Generated by Django 4.0.4 on 2024-11-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0014_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='details',
        ),
    ]
