# Generated by Django 4.0.4 on 2024-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0015_remove_exam_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='details',
            field=models.CharField(default='No Details', max_length=50),
        ),
    ]
