# Generated by Django 5.1.3 on 2024-11-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0017_remove_comment_post_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='file',
        ),
    ]
