# Generated by Django 5.1.3 on 2024-11-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beabee', '0018_remove_homework_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
