# Generated by Django 5.1.3 on 2024-12-20 05:55

import django.contrib.auth.validators
import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('avatar', models.ImageField(upload_to=user.models.avatar_path, verbose_name='avatar')),
                ('nickname', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='nickname')),
                ('first_name', models.CharField(max_length=30, unique=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, unique=True, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=7, verbose_name='sex')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone number')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='city')),
                ('linkedin', models.URLField(blank=True, max_length=100, null=True, verbose_name='linkedin url')),
                ('facebook', models.URLField(blank=True, max_length=100, null=True, verbose_name='facebook url')),
                ('instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='instagram url')),
                ('github', models.URLField(blank=True, max_length=100, null=True, verbose_name='github url')),
                ('group', models.CharField(choices=[('CS-31', 'CS-31'), ('CS-32', 'CS-32'), ('CS-33', 'CS-33'), ('CS-34', 'CS-34'), ('CS-41', 'CS-41'), ('CS-42', 'CS-42'), ('CS-43', 'CS-43'), ('CS-44', 'CS-44')], default='CS-32', max_length=10, verbose_name='group')),
                ('status_in_service', models.CharField(choices=[('Creator', 'Creator'), ('Admin', 'Admin'), ('User', 'User')], db_index=True, default='User', max_length=10, verbose_name='status in service')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.CharField(blank=True, max_length=30, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, help_text='Latitude coordinate', max_digits=20, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=16, help_text='Longitude coordinate', max_digits=20, verbose_name='Longitude')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
                'ordering': ['-user'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='user_gps_latitud_23aae8_idx')],
                'unique_together': {('user', 'latitude', 'longitude')},
            },
        ),
    ]
