# Generated by Django 4.0.4 on 2024-10-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='status_in_service',
            field=models.CharField(choices=[('Creator', 'Creator'), ('Admin', 'Admin'), ('User', 'User')], default='User', max_length=50, verbose_name='status_in_service'),
        ),
    ]
