# Generated by Django 4.0.4 on 2024-11-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gps',
            options={'ordering': ['-user'], 'verbose_name': 'User Location', 'verbose_name_plural': 'User Locations'},
        ),
        migrations.AlterUniqueTogether(
            name='gps',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gps',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='gps',
            index=models.Index(fields=['latitude', 'longitude'], name='user_gps_latitud_23aae8_idx'),
        ),
    ]
