# Generated by Django 4.0.4 on 2024-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_gps_options_alter_gps_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='latitude',
            field=models.DecimalField(decimal_places=20, help_text='Latitude coordinate', max_digits=21, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='longitude',
            field=models.DecimalField(decimal_places=20, help_text='Longitude coordinate', max_digits=21, verbose_name='Longitude'),
        ),
        migrations.AlterUniqueTogether(
            name='gps',
            unique_together={('user', 'latitude', 'longitude')},
        ),
    ]
