# Generated by Django 4.0.4 on 2024-11-02 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_gps_latitude_alter_gps_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='latitude',
            field=models.DecimalField(decimal_places=20, help_text='Latitude coordinate', max_digits=24, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='longitude',
            field=models.DecimalField(decimal_places=20, help_text='Longitude coordinate', max_digits=24, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
